/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bancodelsol;

/**
 *
 * @author rover
 */
public class VistaGenerarRetiro extends javax.swing.JPanel {

    /**
     * Creates new form VistaGenerarRetiro
     */
    public VistaGenerarRetiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        lblMonto = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        lblInformacion = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Amazon Ember", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(149, 120, 64));
        lblTitulo.setText("Generar retiro sin cuenta");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 45, -1, -1));

        txtMonto.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(143, 143, 143));
        txtMonto.setBorder(null);
        add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 400, 36));

        txtContraseña.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(143, 143, 143));
        txtContraseña.setBorder(null);
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 150, 400, 36));

        lblMonto.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(157, 134, 90));
        lblMonto.setText("Ingrese su contraseña:");
        add(lblMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 208, -1, 24));

        lblContrasena.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(157, 134, 90));
        lblContrasena.setText("Monto:");
        add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 117, -1, 24));

        btnSiguiente.setBackground(new java.awt.Color(180, 154, 102));
        btnSiguiente.setFont(new java.awt.Font("Amazon Ember", 0, 18)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 142, 45));

        lblInformacion.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblInformacion.setForeground(new java.awt.Color(143, 143, 143));
        lblInformacion.setText("Más información");
        lblInformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInformacionMouseClicked(evt);
            }
        });
        add(lblInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgRetiroSinCuenta.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed

    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void lblInformacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInformacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblInformacionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
