package bancodelsol;

/**
 * Esta clase representa la vista "Nosotros" de la aplicación.
 * Proporciona información sobre el equipo detrás del banco.
 * Permite al usuario navegar a otras partes de la aplicación, como la página de inicio y el registro.
 * 
 * @author José Karim Franco Valencia - 245138
 * @author Jesús Roberto García Armenta - 244913
 */
public class VistaNosotros extends javax.swing.JPanel {
    private  Ventana ventana;
    
    /**
     * Constructor de la clase VistaNosotros.
     * @param ventana La ventana principal de la aplicación.
     */
    public VistaNosotros(Ventana ventana ) {
        this.ventana = ventana;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInicio = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        btnNosotros = new javax.swing.JButton();
        lblBanco = new javax.swing.JLabel();
        lblEslogan = new javax.swing.JLabel();
        lblPiePagina = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicio.setBackground(new java.awt.Color(143, 143, 143));
        btnInicio.setFont(new java.awt.Font("Amazon Ember Light", 0, 18)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Inicio");
        btnInicio.setBorder(null);
        btnInicio.setBorderPainted(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 105, 129, 36));

        btnRegistro.setBackground(new java.awt.Color(143, 143, 143));
        btnRegistro.setFont(new java.awt.Font("Amazon Ember Light", 0, 16)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistro.setText("Hazte cliente");
        btnRegistro.setBorderPainted(false);
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 105, 129, 36));

        btnNosotros.setBackground(new java.awt.Color(143, 143, 143));
        btnNosotros.setFont(new java.awt.Font("Amazon Ember Light", 0, 18)); // NOI18N
        btnNosotros.setForeground(new java.awt.Color(255, 255, 255));
        btnNosotros.setText("Nosotros");
        btnNosotros.setBorderPainted(false);
        btnNosotros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNosotrosActionPerformed(evt);
            }
        });
        add(btnNosotros, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 105, 129, 36));

        lblBanco.setFont(new java.awt.Font("TrajanusBricks", 0, 44)); // NOI18N
        lblBanco.setForeground(new java.awt.Color(149, 120, 64));
        lblBanco.setText("banco del sol");
        add(lblBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        lblEslogan.setFont(new java.awt.Font("Amazon Ember Light", 0, 18)); // NOI18N
        lblEslogan.setForeground(new java.awt.Color(33, 33, 33));
        add(lblEslogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 230, 70));

        lblPiePagina.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblPiePagina.setForeground(new java.awt.Color(255, 255, 255));
        lblPiePagina.setText("© Banco del Sol 2024");
        add(lblPiePagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 545, 170, 20));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconLogo(2).png"))); // NOI18N
        add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nosotros");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Amazon Ember", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Equipo:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Amazon Ember", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("00000245138 - José Karim Franco Valencia");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Amazon Ember", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("00000244913 - Jesús Roberto García Armenta");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVistaNosotros.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este método se ejecuta cuando el usuario hace clic en el botón "Inicio".
     * Cambia la vista actual a la página de inicio.
     * @param evt El evento de acción que desencadena este método.
     */
    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        ventana.cambiarVistaInicio();
    }//GEN-LAST:event_btnInicioActionPerformed

    /**
     * Este método se ejecuta cuando el usuario hace clic en el botón "Hazte cliente".
     * Cambia la vista actual a la página de registro.
     * @param evt El evento de acción que desencadena este método.
     */
    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
        ventana.cambiarVistaRegistro();
    }//GEN-LAST:event_btnRegistroActionPerformed

    /**
     * Este método se ejecuta cuando el usuario hace clic en el botón "Nosotros".
     * Actualmente no tiene funcionalidad asociada.
     * @param evt El evento de acción que desencadena este método.
     */
    private void btnNosotrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNosotrosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnNosotrosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnNosotros;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblEslogan;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblPiePagina;
    // End of variables declaration//GEN-END:variables
}
