/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bancodelsol;

import bancodelsol.validaciones.ValidadorCampos;
import bancodelsoldominio.Cuenta;
import bancodelsoldominio.Retiro;
import bancodelsolpersistencia.daos.IRetiroDAO;
import bancodelsolpersistencia.daos.RetiroDAO;
import bancodelsolpersistencia.excepciones.PersistenciaException;
import bancodelsolpersistencia.excepciones.TransaccionException;
import bancodelsolpersistencia.excepciones.ValidacionDTOException;
import org.apache.commons.lang3.RandomStringUtils;

/**
 * Panel de la interfaz de usuario para generar un retiro sin cuenta
 *
 * @author José Karim Franco Valencia - 245138
 * @author Jesús Roberto García Armenta - 244913
 */
public class VistaGenerarRetiro extends javax.swing.JPanel {

    Cuenta cuenta;
    private final IRetiroDAO retiroDAO;
    private final Ventana ventana;
    private Retiro retiro;
    double saldoARetirar;
    double saldoRestante;
    private ValidadorCampos validador;
    private boolean retiroValido;

    /**
     * Crea un nuevo panel de VistaGenerarRetiro.
     *
     * @param ventana la ventana de enlace
     */
    public VistaGenerarRetiro(Ventana ventana) {
        this.ventana = ventana;
        cuenta = ventana.getCuenta();
        retiro = new Retiro();

        this.retiroDAO = new RetiroDAO(ventana.getConexion());
        validador = new ValidadorCampos();
        retiroValido = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        lblMonto = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        lblInformacion = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Amazon Ember", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(149, 120, 64));
        lblTitulo.setText("Generar retiro sin cuenta");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 45, -1, -1));

        txtMonto.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(143, 143, 143));
        txtMonto.setBorder(null);
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });
        add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 400, 36));

        txtContraseña.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(143, 143, 143));
        txtContraseña.setBorder(null);
        add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 400, 36));

        lblMonto.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(157, 134, 90));
        lblMonto.setText("Contraseña para retirar:");
        add(lblMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 208, -1, 24));

        lblContrasena.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(157, 134, 90));
        lblContrasena.setText("Monto:");
        add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 117, -1, 24));

        btnSiguiente.setBackground(new java.awt.Color(180, 154, 102));
        btnSiguiente.setFont(new java.awt.Font("Amazon Ember", 0, 18)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 142, 45));

        lblInformacion.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblInformacion.setForeground(new java.awt.Color(143, 143, 143));
        lblInformacion.setText("Más información");
        lblInformacion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblInformacionMouseDragged(evt);
            }
        });
        lblInformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInformacionMouseClicked(evt);
            }
        });
        add(lblInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 190, -1));

        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setFocusPainted(false);
        btnInicio.setFocusable(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 58, 35, 35));

        btnPerfil.setBorderPainted(false);
        btnPerfil.setContentAreaFilled(false);
        btnPerfil.setFocusPainted(false);
        btnPerfil.setFocusable(false);
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 111, 35, 35));

        btnHistorial.setBorderPainted(false);
        btnHistorial.setContentAreaFilled(false);
        btnHistorial.setFocusPainted(false);
        btnHistorial.setFocusable(false);
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 164, 35, 35));

        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.setFocusable(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 213, 35, 35));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgRetiroSinCuenta.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed

        validarRetiro();
        if (!retiroValido) {
            ventana.mostrarAviso("El retiro con los datos acutales no existe");
        }
            generarRetiro();
            ventana.cambiarVistaConfirmarRetiro();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void lblInformacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInformacionMouseClicked
        ventana.cambiarVistaInformacionRetiro();     // TODO add your handling code here:
    }//GEN-LAST:event_lblInformacionMouseClicked

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed

        ventana.cambiarVistaHistorial();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        ventana.cambiarVistaEditarPerfil();
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        ventana.cambiarVistaHistorial();
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        if (ventana.mostrarConfirmacion("¿Seguro que querer cerrar sesión?", "Cerrar sesión")) {
            ventana.setCliente(null);
            ventana.setCuenta(null);
            ventana.cambiarVistaInicio();
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void lblInformacionMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInformacionMouseDragged
        ventana.cambiarVistaInformacionRetiro();     // TODO add your handling code here:
    }//GEN-LAST:event_lblInformacionMouseDragged

    /**
     * Genera un nuevo retiro asignando un folio aleatorio único y la contraseña
     * especificada. Si el folio generado ya existe en la base de datos, se
     * genera otro folio único hasta que se encuentre uno no existente.
     *
     */
    public void generarRetiro() {
        String folio = RandomStringUtils.randomNumeric(8);
        try {
            while (retiroDAO.existeFolio(folio)) {
                folio = RandomStringUtils.randomNumeric(8);
            }
        } catch (PersistenciaException e) {
            ventana.mostrarAviso(e.getMessage());
        }
        retiro.setFolio(folio);
        retiro.setContrasena(txtContraseña.getText());
        retiro.setMonto(saldoARetirar);
        ventana.setRetiro(retiro);
    }

    /**
     * Valida el retiro de fondos ingresado por el usuario antes de procesar la
     * transacción. Verifica que se hayan completado todos los campos requeridos
     * y que el monto del retiro sea válido. Si se detectan problemas durante la
     * validación, se lanzan excepciones específicas para informar al usuario
     * sobre los errores encontrados.
     */
    public void validarRetiro() {
        try {
            verificaCampos();
            validador.validaGenerarRetiro(txtMonto.getText());
            saldoARetirar = Double.parseDouble(txtMonto.getText());
            saldoRestante = retiroDAO.consultarSaldo(ventana.getCuenta(), saldoARetirar);
            retiroValido = true;
        } catch (ValidacionDTOException | PersistenciaException | TransaccionException e) {
            ventana.mostrarAviso(e.getMessage());
        }

    }

    /**
     * Verifica si los campos de monto y contraseña están completos antes de
     * proceder con la validación del retiro. Si alguno de los campos está en
     * blanco, lanza una excepción de ValidacionDTOException con un mensaje
     * indicando al usuario que todos los campos deben ser completados.
     *
     * @throws ValidacionDTOException si alguno de los campos está en blanco
     */
    private void verificaCampos() throws ValidacionDTOException {
        if (txtMonto.getText().isBlank() || txtContraseña.getText().isBlank()) {
            throw new ValidacionDTOException("Llene todos los campos");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
