package bancodelsol;

import bancodelsoldominio.Cliente;
import bancodelsoldominio.Cuenta;
import bancodelsoldominio.Domicilio;
import bancodelsolpersistencia.daos.ClienteDAO;
import bancodelsolpersistencia.daos.CuentaDAO;
import bancodelsolpersistencia.daos.DomicilioDAO;
import bancodelsolpersistencia.daos.IClienteDAO;
import bancodelsolpersistencia.daos.ICuentaDAO;
import bancodelsolpersistencia.excepciones.PersistenciaException;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Clase que representa la vista de un cliente en el sistema bancario. Esta
 * clase contiene componentes de interfaz de usuario para mostrar información
 * sobre las cuentas del cliente. Además, gestiona la recuperación de cuentas
 * del cliente y la visualización de detalles de cuenta seleccionada.
 *
 * @author José Karim Franco Valencia - 245138
 * @author Jesús Roberto García Armenta - 244913
 */
public class VistaCliente extends javax.swing.JPanel {

    private Ventana ventana;
    private Cliente clienteActual;
    private List<Cuenta> listaCuentas;

    /**
     * Constructor de la clase VistaCliente.
     *
     * @param ventana La ventana principal de la aplicación.
     */
    public VistaCliente(Ventana ventana) {
        this.ventana = ventana;
        clienteActual = ventana.getCliente();
        this.listaCuentas = new LinkedList<>();
        initComponents();

        asignarDomicilio();
        recuperarCuentas();
        generarDatos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarCuenta = new javax.swing.JButton();
        btnCuentaSeleccionada = new javax.swing.JButton();
        cbxCuentas = new javax.swing.JComboBox<>();
        lblNombreCliente = new javax.swing.JLabel();
        lblCuentaInfo = new javax.swing.JLabel();
        lblNombreCuenta = new javax.swing.JLabel();
        lblNumeroCuenta = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblAgregarCuenta = new javax.swing.JLabel();
        iconAjustes = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        iconInicio = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JButton();
        iconPerfil = new javax.swing.JLabel();
        btnHistorial = new javax.swing.JButton();
        iconHistorial = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        iconCerrarSesion = new javax.swing.JLabel();
        iconLogo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarCuenta.setBorderPainted(false);
        btnAgregarCuenta.setContentAreaFilled(false);
        btnAgregarCuenta.setFocusPainted(false);
        btnAgregarCuenta.setFocusable(false);
        btnAgregarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCuentaActionPerformed(evt);
            }
        });
        add(btnAgregarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 153, 200, 140));

        btnCuentaSeleccionada.setBorderPainted(false);
        btnCuentaSeleccionada.setContentAreaFilled(false);
        btnCuentaSeleccionada.setFocusPainted(false);
        btnCuentaSeleccionada.setFocusable(false);
        btnCuentaSeleccionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentaSeleccionadaActionPerformed(evt);
            }
        });
        add(btnCuentaSeleccionada, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 153, 205, 140));

        cbxCuentas.setFont(new java.awt.Font("Amazon Ember Light", 0, 18)); // NOI18N
        cbxCuentas.setForeground(new java.awt.Color(157, 134, 90));
        cbxCuentas.setFocusable(false);
        cbxCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCuentasActionPerformed(evt);
            }
        });
        add(cbxCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 302, 205, 39));

        lblNombreCliente.setFont(new java.awt.Font("Amazon Ember", 1, 36)); // NOI18N
        lblNombreCliente.setForeground(new java.awt.Color(149, 120, 64));
        lblNombreCliente.setText("(nombre de usuario)");
        add(lblNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 820, 43));

        lblCuentaInfo.setFont(new java.awt.Font("Amazon Ember", 1, 24)); // NOI18N
        lblCuentaInfo.setForeground(new java.awt.Color(143, 143, 143));
        lblCuentaInfo.setText("Cuentas");
        add(lblCuentaInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 115, 284, 30));

        lblNombreCuenta.setFont(new java.awt.Font("Amazon Ember", 0, 20)); // NOI18N
        lblNombreCuenta.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreCuenta.setText("Hogar");
        add(lblNombreCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 170, 170, 24));

        lblNumeroCuenta.setFont(new java.awt.Font("Amazon Ember Light", 1, 20)); // NOI18N
        lblNumeroCuenta.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroCuenta.setText("4444555566667777");
        add(lblNumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 160, 24));

        lblSaldo.setFont(new java.awt.Font("Amazon Ember", 1, 22)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(255, 255, 255));
        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaldo.setText("$112.00 MXN");
        add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 180, 24));

        lblAgregarCuenta.setFont(new java.awt.Font("Amazon Ember", 1, 22)); // NOI18N
        lblAgregarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregarCuenta.setText("Agregar cuenta +");
        add(lblAgregarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 200, -1));

        iconAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconAjustes.png"))); // NOI18N
        add(iconAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 10, 35, 35));

        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setFocusPainted(false);
        btnInicio.setFocusable(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 58, 35, 35));

        iconInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconInicio.png"))); // NOI18N
        add(iconInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 58, 35, 35));

        btnPerfil.setBorderPainted(false);
        btnPerfil.setContentAreaFilled(false);
        btnPerfil.setFocusPainted(false);
        btnPerfil.setFocusable(false);
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 111, 35, 35));

        iconPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPerfil.png"))); // NOI18N
        add(iconPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 111, 35, 35));

        btnHistorial.setBorderPainted(false);
        btnHistorial.setContentAreaFilled(false);
        btnHistorial.setFocusPainted(false);
        btnHistorial.setFocusable(false);
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 164, 35, 35));

        iconHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconHistorial.png"))); // NOI18N
        add(iconHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 164, 35, 35));

        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.setFocusable(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 213, 35, 35));

        iconCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconCerrarSesion.png"))); // NOI18N
        add(iconCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 213, 35, 35));

        iconLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconLogo.png"))); // NOI18N
        add(iconLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 538, 35, 35));

        fondo.setBackground(new java.awt.Color(102, 102, 102));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVistaCliente.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que cambia la vista actual a la vista de creación de cuenta.
     *
     * @param evt El evento de acción que desencadena este método (clic en el
     * botón agregar cuenta).
     */
    private void btnAgregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCuentaActionPerformed
        ventana.cambiarVistaCrearCuenta();
    }//GEN-LAST:event_btnAgregarCuentaActionPerformed
    /**
     * Método que obtiene la cuenta seleccionada del combo box y cambia la vista
     * a la vista de detalles de la cuenta.
     *
     * @param evt El evento de acción que desencadena este método (clic en el
     * botón de cuenta seleccionada).
     */
    private void btnCuentaSeleccionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentaSeleccionadaActionPerformed
        // TODO add your handling code here:
        if (cbxCuentas.isEnabled()) {
            Cuenta cuentaSeleccionada = listaCuentas.get(cbxCuentas.getSelectedIndex());
            ventana.setCuenta(cuentaSeleccionada);
            ventana.cambiarVistaCuenta();
        }
    }//GEN-LAST:event_btnCuentaSeleccionadaActionPerformed

    private void cbxCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCuentasActionPerformed
        Cuenta cuentaSeleccionada = listaCuentas.get(cbxCuentas.getSelectedIndex());

        lblNombreCuenta.setText(cuentaSeleccionada.getNombreCuenta());
        lblNumeroCuenta.setText(cuentaSeleccionada.getNumeroCuenta());
        String numeroFormateado = String.format("%.2f", cuentaSeleccionada.getSaldo());

        lblSaldo.setText("$" + numeroFormateado + " MXN");
    }//GEN-LAST:event_cbxCuentasActionPerformed

    /**
     * Cambia la vista actual a la vista principal del cliente.
     *
     * @param evt El evento de acción que desencadena este método.
     */
    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed

    }//GEN-LAST:event_btnInicioActionPerformed

    /**
     * Cambia la vista del perfil del cliente.
     *
     * @param evt El evento de acción que desencadena este método.
     */
    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        ventana.cambiarVistaEditarPerfil();
    }//GEN-LAST:event_btnPerfilActionPerformed

    /**
     * Cambia la vista del historial de operaciones totales.
     *
     * @param evt El evento de acción que desencadena este método.
     */
    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        ventana.cambiarVistaHistorial();
    }//GEN-LAST:event_btnHistorialActionPerformed

    /**
     * Cambia la vista actual a la pantalla de inicio del banco.
     *
     * @param evt El evento de acción que desencadena este método.
     */
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        if (ventana.mostrarConfirmacion("¿Seguro que querer cerrar sesión?", "Cerrar sesión")) {
            ventana.setCliente(null);
            ventana.setCuenta(null);
            ventana.cambiarVistaInicio();
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * Método que recupera las cuentas existentes del cliente
     */
    private void recuperarCuentas() {
        listaCuentas = new LinkedList<>();
        try {
            ICuentaDAO cuentaDAO = new CuentaDAO(ventana.getConexion());
            listaCuentas = cuentaDAO.consultar(clienteActual.getIdCliente());
            insertarCuentas();
        } catch (PersistenciaException ex) {
            ventana.mostrarAviso(ex.getMessage());
//            Logger.getLogger(VistaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * Inserta las cuentas recuperadas del cliente en el combo box de cuentas.
     * Si no hay cuentas disponibles, deshabilita el combo box.
     */
    private void insertarCuentas() {
        if (listaCuentas.isEmpty()) {
            cbxCuentas.setEnabled(false);

            lblNombreCuenta.setText("Cree una cuenta");
            lblNumeroCuenta.setText("--------");
            lblSaldo.setText("");
        } else {
            cbxCuentas.setEnabled(true);
            for (Cuenta cuenta : listaCuentas) {
                cbxCuentas.addItem(cuenta.getNombreCuenta());
            }

        }
    }

    /**
     * Genera los datos del cliente actual y los muestra en la interfaz gráfica.
     * Utiliza el nombre y apellido paterno del cliente actual para saludarlo en
     * un JLabel.
     */
    private void generarDatos() {
        lblNombreCliente.setText("Hola, " + clienteActual.getNombre() + " " + clienteActual.getApellidoPaterno());
    }

    /**
     * Asigna el domicilio del cliente actual obtenido de la base de datos a la
     * ventana. Utiliza un objeto DomicilioDAO para obtener el domicilio del
     * cliente actual a partir de su ID. Si se produce un error al acceder a la
     * base de datos, registra el error en los logs.
     */
    private void asignarDomicilio() {
        try {
            DomicilioDAO domicilioDAO = new DomicilioDAO(ventana.getConexion());
            Domicilio domicilioAux = domicilioDAO.existe(clienteActual.getIdCliente());
            ventana.setDomicilio(domicilioAux);
        } catch (PersistenciaException ex) {
            Logger.getLogger(VistaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCuenta;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCuentaSeleccionada;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JComboBox<String> cbxCuentas;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel iconAjustes;
    private javax.swing.JLabel iconCerrarSesion;
    private javax.swing.JLabel iconHistorial;
    private javax.swing.JLabel iconInicio;
    private javax.swing.JLabel iconLogo;
    private javax.swing.JLabel iconPerfil;
    private javax.swing.JLabel lblAgregarCuenta;
    private javax.swing.JLabel lblCuentaInfo;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNombreCuenta;
    private javax.swing.JLabel lblNumeroCuenta;
    private javax.swing.JLabel lblSaldo;
    // End of variables declaration//GEN-END:variables
}
