/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bancodelsol;

/**
 *
 * @author rover
 */
public class VistaInformacionRetiro extends javax.swing.JPanel {

    Ventana ventana;
    /**
     * Creates new form VistaInformacionRetiro
     */
    public VistaInformacionRetiro(Ventana ventana) {
        this.ventana = ventana;
        initComponents();
        lblInfo.setText("""
                <html><p>El retiro sin cuenta es un servicio proporcionado <br> 
                        por el banco que te permite realizar un retiro con un folio <br>
                        y una contraseña generados por una cuenta. El tiempo válido<br>
                        para realizar el retiro es de 10 minutos. Pasado este tiempo, <br>
                        el folio y la contraseña se vencen y ya no son válidos.</p></html>""");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfo = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInfo.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(33, 33, 33));
        lblInfo.setText("jLabel1");
        add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        btnAceptar.setBackground(new java.awt.Color(180, 154, 102));
        btnAceptar.setFont(new java.awt.Font("Amazon Ember", 0, 20)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(253, 253, 253));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 140, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgConfirmarRetiroSinCuenta.png"))); // NOI18N
        fondo.setText("jLabel1");
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        ventana.cambiarVistaGenerarRetiro();
        
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblInfo;
    // End of variables declaration//GEN-END:variables
}
