/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bancodelsol;

/**
 *
 * @author karim
 */
public class VistaInicioSesion extends javax.swing.JPanel {

    /**
     * Creates new form VistaInicioSesion
     */
    private  Ventana ventana;
    /**
     * Creates new form VistaCliente
     */
    public VistaInicioSesion(Ventana ventana ) {
        this.ventana = ventana;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JTextField();
        lblBanco = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        btnInicioSesion = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        lblHazteCliente = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(143, 143, 143));
        txtUsuario.setBorder(null);
        add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 240, 447, 37));

        txtContrasena.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtContrasena.setForeground(new java.awt.Color(143, 143, 143));
        txtContrasena.setBorder(null);
        add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 327, 447, 37));

        lblBanco.setFont(new java.awt.Font("TrajanusBricks", 0, 36)); // NOI18N
        lblBanco.setForeground(new java.awt.Color(149, 120, 64));
        lblBanco.setText("BANCO DEL SOL");
        add(lblBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 21, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Amazon Ember", 1, 54)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(143, 143, 143));
        lblTitulo.setText("Inicio Sesión");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 130, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(157, 134, 90));
        lblUsuario.setText("Usuario:");
        add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 212, -1, 24));

        lblContrasena.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(157, 134, 90));
        lblContrasena.setText("Contrasena");
        add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 299, -1, 24));

        btnInicioSesion.setBackground(new java.awt.Color(180, 154, 102));
        btnInicioSesion.setFont(new java.awt.Font("Amazon Ember", 0, 18)); // NOI18N
        btnInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnInicioSesion.setText("Inicio Sesión");
        btnInicioSesion.setBorderPainted(false);
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });
        add(btnInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 142, 45));

        btnInicio.setBackground(new java.awt.Color(180, 154, 102));
        btnInicio.setFont(new java.awt.Font("Amazon Ember", 0, 18)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Volver");
        btnInicio.setBorderPainted(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 142, 45));

        lblHazteCliente.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblHazteCliente.setForeground(new java.awt.Color(143, 143, 143));
        lblHazteCliente.setText("¿No eres cliente y quieres serlo?");
        add(lblHazteCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgInicioSesion.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioSesionActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnInicioSesion;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblHazteCliente;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
