/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bancodelsol;

import bancodelsol.dtos.TransferenciaNuevaDTO;
import bancodelsoldominio.Cuenta;
import bancodelsolpersistencia.conexion.Conexion;
import bancodelsolpersistencia.conexion.IConexion;
import bancodelsolpersistencia.daos.CuentaDAO;
import bancodelsolpersistencia.daos.ITransferenciaDAO;
import bancodelsolpersistencia.daos.TransferenciaDAO;
import bancodelsolpersistencia.excepciones.PersistenciaException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author karim
 */
public class VistaTransferir extends javax.swing.JPanel {
    Cuenta cuenta;
    Long idCuenta;
    /**
     * Creates new form VistaCliente
     */
    private  Ventana ventana;
    /**
     * Creates new form VistaCliente
     */
    public VistaTransferir(Ventana ventana, Long idCuenta ) {
        this.ventana = ventana;
        this.idCuenta = idCuenta;
        initComponents();
        cargarDatosCuenta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNombreCuentaInfo = new javax.swing.JLabel();
        lblSaldoInfo = new javax.swing.JLabel();
        lblNumCuentaInfo = new javax.swing.JLabel();
        lblNombreCuenta = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblNumCuenta = new javax.swing.JLabel();
        lblCuentaDestino = new javax.swing.JLabel();
        txtCuentaDestino = new javax.swing.JTextField();
        lblMonto = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnTransferir = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Amazon Ember", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(149, 120, 64));
        lblTitulo.setText("Transferir");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 34, 180, 43));

        lblNombreCuentaInfo.setFont(new java.awt.Font("Amazon Ember", 1, 22)); // NOI18N
        lblNombreCuentaInfo.setForeground(new java.awt.Color(168, 163, 154));
        lblNombreCuentaInfo.setText("Cuenta:");
        add(lblNombreCuentaInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 105, 80, 26));

        lblSaldoInfo.setFont(new java.awt.Font("Amazon Ember", 1, 22)); // NOI18N
        lblSaldoInfo.setForeground(new java.awt.Color(168, 163, 154));
        lblSaldoInfo.setText("Saldo actual:");
        add(lblSaldoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 105, -1, 26));

        lblNumCuentaInfo.setFont(new java.awt.Font("Amazon Ember", 1, 22)); // NOI18N
        lblNumCuentaInfo.setForeground(new java.awt.Color(168, 163, 154));
        lblNumCuentaInfo.setText("# de cuenta:");
        add(lblNumCuentaInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 105, -1, 26));

        lblNombreCuenta.setFont(new java.awt.Font("Amazon Ember", 1, 22)); // NOI18N
        lblNombreCuenta.setForeground(new java.awt.Color(180, 154, 102));
        lblNombreCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreCuenta.setText("Cuenta:");
        lblNombreCuenta.setToolTipText("");
        add(lblNombreCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 131, 120, 26));

        lblSaldo.setFont(new java.awt.Font("Amazon Ember", 1, 36)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(180, 154, 102));
        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaldo.setText("$112.00 MXN");
        add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 133, 305, 43));

        lblNumCuenta.setFont(new java.awt.Font("Amazon Ember", 1, 22)); // NOI18N
        lblNumCuenta.setForeground(new java.awt.Color(180, 154, 102));
        lblNumCuenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNumCuenta.setText("1111222211112222");
        add(lblNumCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 131, 230, 26));

        lblCuentaDestino.setFont(new java.awt.Font("Amazon Ember Light", 1, 20)); // NOI18N
        lblCuentaDestino.setForeground(new java.awt.Color(180, 154, 102));
        lblCuentaDestino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCuentaDestino.setText("Num. Cuenta Destino:");
        add(lblCuentaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 229, -1, -1));

        txtCuentaDestino.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtCuentaDestino.setForeground(new java.awt.Color(143, 143, 143));
        add(txtCuentaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 259, 406, 40));

        lblMonto.setFont(new java.awt.Font("Amazon Ember Light", 1, 20)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(180, 154, 102));
        lblMonto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMonto.setText("Monto:");
        add(lblMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 320, -1, -1));

        txtMonto.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(143, 143, 143));
        add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 350, 406, 40));

        jButton1.setBackground(new java.awt.Color(180, 154, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancelar");
        jButton1.setBorderPainted(false);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 446, 142, 45));

        btnTransferir.setBackground(new java.awt.Color(180, 154, 102));
        btnTransferir.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnTransferir.setForeground(new java.awt.Color(255, 255, 255));
        btnTransferir.setText("Transferir");
        btnTransferir.setBorderPainted(false);
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });
        add(btnTransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 446, 142, 45));
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        try {
            // TODO add your handling code here:
            String cadenaConexion = "jdbc:mysql://localhost/banco_del_sol";
            String user = "root";
            String password = "JFK_jfk27";
            IConexion conexion = new Conexion(cadenaConexion, user, password);
            ITransferenciaDAO transferenciaDAO = new TransferenciaDAO(conexion);
            TransferenciaNuevaDTO transferenciaNueva = new TransferenciaNuevaDTO();
            transferenciaNueva.setMonto(Double.parseDouble(txtMonto.getText()));
            transferenciaNueva.setCuentaDestino(txtCuentaDestino.getText());
            transferenciaDAO.agregar(transferenciaNueva,idCuenta);
        } catch (PersistenciaException ex) {
            Logger.getLogger(VistaTransferir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTransferirActionPerformed

    public void cargarDatosCuenta(){
        try {
            String cadenaConexion = "jdbc:mysql://localhost/banco_del_sol";
            String user = "root";
            String password = "JFK_jfk27";
            
            IConexion conexion = new Conexion(cadenaConexion, user, password);
            
            CuentaDAO cuentaDAO = new CuentaDAO(conexion);
            this.cuenta = cuentaDAO.existe(this.idCuenta);
            
            if(cuenta != null){
//                System.out.println(cuenta.toString());
                lblNombreCuenta.setText("Hogar");
                lblSaldo.setText("$"+this.cuenta.getSaldo()+" MXN");
                lblNumCuenta.setText(cuenta.getNumeroCuenta());
            }
        } catch (PersistenciaException ex) {
            Logger.getLogger(VistaCuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransferir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCuentaDestino;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNombreCuenta;
    private javax.swing.JLabel lblNombreCuentaInfo;
    private javax.swing.JLabel lblNumCuenta;
    private javax.swing.JLabel lblNumCuentaInfo;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSaldoInfo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCuentaDestino;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
