/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bancodelsol;

import bancodelsoldominio.Cuenta;
import bancodelsoldominio.Retiro;
import bancodelsolpersistencia.daos.IRetiroDAO;
import bancodelsolpersistencia.daos.ITransaccionDAO;
import bancodelsolpersistencia.daos.RetiroDAO;
import bancodelsolpersistencia.daos.TransaccionDAO;
import bancodelsolpersistencia.excepciones.PersistenciaException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Panel que muestra la confirmación de un retiro sin cuenta. Permite al usuario
 * revisar los detalles del retiro antes de confirmarlo. Muestra información
 * como el número de folio, el número de cuenta y la cantidad a retirar. Permite
 * al usuario retroceder para realizar cambios en el retiro o avanzar para
 * confirmarlo.
 *
 * @author José Karim Franco Valencia - 245138
 * @author Jesús Roberto García Armenta - 244913
 */
public class VistaConfirmarEfectuarRetiro extends javax.swing.JPanel {

    private final IRetiroDAO retiroDAO;
    private final Ventana ventana;
    private final ITransaccionDAO transaccionDAO;

    private boolean retiroValido;

    /**
     * Crea un nuevo panel de VistaGenerarRetiro.
     *
     * @param ventana la ventana de enlace
     */
    public VistaConfirmarEfectuarRetiro(Ventana ventana) {
        this.ventana = ventana;
        this.retiroDAO = new RetiroDAO(ventana.getConexion());
        this.transaccionDAO = new TransaccionDAO(ventana.getConexion());
        retiroValido = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        bntAtras = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        lblContrasena1 = new javax.swing.JLabel();
        lblCuenta = new javax.swing.JLabel();
        lblContrasena4 = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblFolio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Amazon Ember", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(149, 120, 64));
        lblTitulo.setText("Realizar retiro sin cuenta");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        lblContrasena.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(157, 134, 90));
        lblContrasena.setText("Num. de Cuenta");
        add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, 24));

        bntAtras.setBackground(new java.awt.Color(180, 154, 102));
        bntAtras.setFont(new java.awt.Font("Amazon Ember", 0, 18)); // NOI18N
        bntAtras.setForeground(new java.awt.Color(255, 255, 255));
        bntAtras.setText("Volver");
        bntAtras.setBorderPainted(false);
        bntAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAtrasActionPerformed(evt);
            }
        });
        add(bntAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 142, 45));

        btnSiguiente.setBackground(new java.awt.Color(180, 154, 102));
        btnSiguiente.setFont(new java.awt.Font("Amazon Ember", 0, 18)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Confirmar");
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 142, 45));

        lblContrasena1.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblContrasena1.setForeground(new java.awt.Color(157, 134, 90));
        lblContrasena1.setText("Cantidad a retirar");
        add(lblContrasena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, 24));

        lblCuenta.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblCuenta.setForeground(new java.awt.Color(30, 30, 30));
        lblCuenta.setText("numero de cuenta");
        add(lblCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, 24));

        lblContrasena4.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblContrasena4.setForeground(new java.awt.Color(157, 134, 90));
        lblContrasena4.setText("No. de Folio");
        add(lblContrasena4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, 24));

        lblCantidad.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(30, 30, 30));
        lblCantidad.setText("monto");
        add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, 24));

        lblFolio.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblFolio.setForeground(new java.awt.Color(30, 30, 30));
        lblFolio.setText("folio");
        add(lblFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, 24));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVistaEditarPerfil.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cambia la vista a la pantalla de efectuar retiro cuando se hace clic en
     * el botón "Atras".
     *
     * @param evt El evento de acción del botón "Atras".
     */
    private void bntAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAtrasActionPerformed
        ventana.cambiarVistaEfectuarRetiro();
    }//GEN-LAST:event_bntAtrasActionPerformed

    /**
     * Cambia la vista a la pantalla de confirmar efectuar retiro cuando se hace
     * clic en el botón "Siguiente".
     *
     * @param evt El evento de acción del botón "Siguiente".
     */
    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if (ventana.mostrarConfirmacion("Deseas efectuar el retiro?", "Confirmar retiro")) {
            ventana.cambiarVistaCuenta();
        }
        ;
    }//GEN-LAST:event_btnSiguienteActionPerformed

    
    public void retirar(){
        try {
            transaccionDAO.realizarRetiro(ventana.getRetiro().getFolio(), ventana.getRetiro().getContrasena());
        } catch (PersistenciaException ex) {
            ventana.mostrarAviso(ex.getMessage());
        }
    }
    /**
     * Actualiza los componentes de la interfaz con la información del retiro y
     * la cuenta.
     *
     * Actualiza los JLabels "lblFolio" y "lblCuenta" con la información
     * correspondiente del retiro y la cuenta.
     */
    public void setTexts() {
        lblFolio.setText(ventana.getRetiro().getFolio());
        lblCuenta.setText(ventana.getCuenta().getNumeroCuenta());
//        lblFolio.setText(ventana.get);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAtras;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblContrasena1;
    private javax.swing.JLabel lblContrasena4;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblFolio;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
