/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bancodelsol;

/**
 *
 * @author karim
 */
public class VistaTransferenciaExitosa extends javax.swing.JPanel {

    /**
     * Creates new form VistaTransferenciaExitosa
     */
    public VistaTransferenciaExitosa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTransferenciaExitosaInfo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblFechaHora = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblMotivo = new javax.swing.JLabel();
        lblMensaje1 = new javax.swing.JLabel();
        lblCuentaInfo = new javax.swing.JLabel();
        lblNumeroCuenta = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTransferenciaExitosaInfo.setFont(new java.awt.Font("Amazon Ember", 1, 48)); // NOI18N
        lblTransferenciaExitosaInfo.setForeground(new java.awt.Color(143, 143, 143));
        lblTransferenciaExitosaInfo.setText("Transferencia exitosa");
        add(lblTransferenciaExitosaInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 163, -1, -1));

        lblLogo.setFont(new java.awt.Font("TrajanusBricks", 0, 36)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(157, 134, 90));
        lblLogo.setText("BANCO DEL SOL");
        add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblFechaHora.setFont(new java.awt.Font("Amazon Ember Light", 1, 20)); // NOI18N
        lblFechaHora.setForeground(new java.awt.Color(34, 33, 33));
        lblFechaHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaHora.setText("datos fecha ...");
        add(lblFechaHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 237, 477, 23));

        lblSaldo.setFont(new java.awt.Font("Amazon Ember", 1, 40)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(180, 154, 102));
        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaldo.setText("$000.00 MXN");
        add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 271, 477, -1));

        lblMotivo.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        lblMotivo.setForeground(new java.awt.Color(34, 33, 33));
        lblMotivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMotivo.setText("X motivo");
        lblMotivo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 350, 477, 50));

        lblMensaje1.setFont(new java.awt.Font("Amazon Ember Light", 0, 12)); // NOI18N
        lblMensaje1.setForeground(new java.awt.Color(34, 33, 33));
        lblMensaje1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje1.setText("Esta transferencia no genera comisión");
        add(lblMensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 324, 477, 23));

        lblCuentaInfo.setFont(new java.awt.Font("Amazon Ember", 1, 22)); // NOI18N
        lblCuentaInfo.setForeground(new java.awt.Color(143, 143, 143));
        lblCuentaInfo.setText("Cuenta:");
        add(lblCuentaInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        lblNumeroCuenta.setFont(new java.awt.Font("Amazon Ember", 1, 22)); // NOI18N
        lblNumeroCuenta.setForeground(new java.awt.Color(168, 163, 154));
        lblNumeroCuenta.setText("2710-9090");
        add(lblNumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 220, -1));

        btnAceptar.setBackground(new java.awt.Color(180, 154, 102));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorderPainted(false);
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 142, 45));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVistaTransfenciaExitosa.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblCuentaInfo;
    private javax.swing.JLabel lblFechaHora;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMensaje1;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblNumeroCuenta;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTransferenciaExitosaInfo;
    // End of variables declaration//GEN-END:variables
}
