/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bancodelsol;

import bancodelsol.validaciones.ValidadorCampos;
import bancodelsoldominio.Cuenta;
import bancodelsolpersistencia.daos.IRetiroDAO;
import bancodelsolpersistencia.daos.RetiroDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author rover
 */
public class vistaMostrarDatosRetiro extends javax.swing.JPanel {

    private final IRetiroDAO retiroDAO;
    private final Ventana ventana;
    
    /**
     * Creates new form vistaMostrarDatosRetiro
     */
    public vistaMostrarDatosRetiro(Ventana ventana) {
        this.ventana = ventana;
        this.retiroDAO = new RetiroDAO(ventana.getConexion());
        initComponents();
        setTextos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConfirmar = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        lblFolio = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        lblInfo3 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConfirmar.setFont(new java.awt.Font("Amazon Ember", 1, 40)); // NOI18N
        lblConfirmar.setForeground(new java.awt.Color(143, 143, 143));
        lblConfirmar.setText("Datos del retiro:");
        add(lblConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        lblInfo.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(33, 33, 33));
        lblInfo.setText("Folio:");
        add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        btnAceptar.setBackground(new java.awt.Color(180, 154, 102));
        btnAceptar.setFont(new java.awt.Font("Amazon Ember", 0, 20)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(253, 253, 253));
        btnAceptar.setText("Continuar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 140, 50));

        lblFolio.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblFolio.setForeground(new java.awt.Color(33, 33, 33));
        lblFolio.setText("(folio)");
        add(lblFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        lblContrasena.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(33, 33, 33));
        lblContrasena.setText("(contraseña)");
        add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        lblInfo3.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        lblInfo3.setForeground(new java.awt.Color(33, 33, 33));
        lblInfo3.setText("Contraseña:");
        add(lblInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgConfirmarRetiroSinCuenta.png"))); // NOI18N
        fondo.setText("jLabel1");
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if(ventana.mostrarConfirmacion("Asegurese de guardar el folio y contraseña", "Ir a inicio")){
                ventana.cambiarVistaCuenta();
            }
    }//GEN-LAST:event_btnAceptarActionPerformed

    public void setTextos(){
        lblFolio.setText(ventana.getRetiro().getFolio());
        lblContrasena.setText(ventana.getRetiro().getContrasena());
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblConfirmar;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblFolio;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblInfo3;
    // End of variables declaration//GEN-END:variables
}
