package bancodelsol;

import bancodelsol.dtos.ClienteNuevoDTO;
import bancodelsol.dtos.DomicilioNuevoDTO;
import bancodelsol.validaciones.ValidadorCampos;
import bancodelsoldominio.Cliente;
import bancodelsoldominio.Domicilio;
import bancodelsolpersistencia.daos.ClienteDAO;
import bancodelsolpersistencia.daos.DomicilioDAO;
import bancodelsolpersistencia.daos.IClienteDAO;
import bancodelsolpersistencia.daos.IDomicilioDAO;
import bancodelsolpersistencia.excepciones.PersistenciaException;
import bancodelsolpersistencia.excepciones.ValidacionDTOException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 * Clase que representa la vista de edición de perfil del cliente en el sistema bancario.
 * Esta clase proporciona componentes de interfaz de usuario para que el cliente pueda editar su información personal y de domicilio.
 * Además, gestiona la navegación entre diferentes vistas de la aplicación.
 * 
 * @author José Karim Franco Valencia - 245138
 * @author Jesús Roberto García Armenta - 244913
 */
public class VistaEditarPerfil extends javax.swing.JPanel {

    private Ventana ventana;
    private Cliente clienteActual;
    private Domicilio domicilioActual;
    private ClienteNuevoDTO clienteDTO;
    private DomicilioNuevoDTO domicilioDTO;
    private boolean camposValidados;

    /**
     * Constructor de la clase VistaEditarPerfil.
     *
     * @param ventana La ventana principal de la aplicación.
     */
    public VistaEditarPerfil(Ventana ventana) {
        this.ventana = ventana;
        this.clienteActual = ventana.getCliente();
        this.domicilioActual = ventana.getDomicilio();
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNombres1 = new javax.swing.JLabel();
        lblDomicilio = new javax.swing.JLabel();
        iconAjustes = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        iconInicio = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JButton();
        iconPerfil = new javax.swing.JLabel();
        btnHistorial = new javax.swing.JButton();
        iconHistorial = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        iconCerrarSesion = new javax.swing.JLabel();
        iconLogo = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardarCambios = new javax.swing.JButton();
        lblNombres = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellidoPaterno = new javax.swing.JLabel();
        txtApellidoPaterno = new javax.swing.JTextField();
        lblApellidoMaterno = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        txtColonia = new javax.swing.JTextField();
        lblUsuario1 = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        lblNombres2 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        lblContrasena1 = new javax.swing.JLabel();
        txtNumeroExterior = new javax.swing.JTextField();
        lblApellidoPaterno1 = new javax.swing.JLabel();
        txtCodigoPostal = new javax.swing.JTextField();
        lblApellidoMaterno1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Amazon Ember Light", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(143, 143, 143));
        lblTitulo.setText("Nombre Cliente completo");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 37, 710, 43));

        lblNombres1.setFont(new java.awt.Font("Amazon Ember", 1, 24)); // NOI18N
        lblNombres1.setForeground(new java.awt.Color(180, 154, 102));
        lblNombres1.setText("Datos personales:");
        add(lblNombres1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        lblDomicilio.setFont(new java.awt.Font("Amazon Ember", 1, 24)); // NOI18N
        lblDomicilio.setForeground(new java.awt.Color(180, 154, 102));
        lblDomicilio.setText("Datos de domicilio:");
        add(lblDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        iconAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconAjustes.png"))); // NOI18N
        add(iconAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 10, 35, 35));

        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setFocusPainted(false);
        btnInicio.setFocusable(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 58, 35, 35));

        iconInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconInicio.png"))); // NOI18N
        add(iconInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 58, 35, 35));

        btnPerfil.setBorderPainted(false);
        btnPerfil.setContentAreaFilled(false);
        btnPerfil.setFocusPainted(false);
        btnPerfil.setFocusable(false);
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 111, 35, 35));

        iconPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPerfil.png"))); // NOI18N
        add(iconPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 111, 35, 35));

        btnHistorial.setBorderPainted(false);
        btnHistorial.setContentAreaFilled(false);
        btnHistorial.setFocusPainted(false);
        btnHistorial.setFocusable(false);
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 164, 35, 35));

        iconHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconHistorial.png"))); // NOI18N
        add(iconHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 164, 35, 35));

        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.setFocusable(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 213, 35, 35));

        iconCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconCerrarSesion.png"))); // NOI18N
        add(iconCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 213, 35, 35));

        iconLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconLogo.png"))); // NOI18N
        add(iconLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 538, 35, 35));

        btnCancelar.setBackground(new java.awt.Color(143, 143, 143));
        btnCancelar.setFont(new java.awt.Font("Amazon Ember", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, 150, 45));

        btnEditar.setBackground(new java.awt.Color(180, 154, 102));
        btnEditar.setFont(new java.awt.Font("Amazon Ember", 0, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar datos");
        btnEditar.setBorderPainted(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, 150, 45));

        btnGuardarCambios.setBackground(new java.awt.Color(180, 154, 102));
        btnGuardarCambios.setFont(new java.awt.Font("Amazon Ember", 0, 18)); // NOI18N
        btnGuardarCambios.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarCambios.setText("Guardar datos");
        btnGuardarCambios.setBorderPainted(false);
        btnGuardarCambios.setEnabled(false);
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });
        add(btnGuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 510, 160, 45));

        lblNombres.setFont(new java.awt.Font("Amazon Ember", 1, 20)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(143, 143, 143));
        lblNombres.setText("Nombres:");
        add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(180, 154, 102));
        txtNombre.setText("nombreCliente");
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143, 143, 143)));
        txtNombre.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 250, 36));

        lblApellidoPaterno.setFont(new java.awt.Font("Amazon Ember", 1, 20)); // NOI18N
        lblApellidoPaterno.setForeground(new java.awt.Color(143, 143, 143));
        lblApellidoPaterno.setText("Apellido Paterno:");
        lblApellidoPaterno.setEnabled(false);
        add(lblApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        txtApellidoPaterno.setEditable(false);
        txtApellidoPaterno.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtApellidoPaterno.setForeground(new java.awt.Color(180, 154, 102));
        txtApellidoPaterno.setText("nombreCliente");
        txtApellidoPaterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143, 143, 143)));
        txtApellidoPaterno.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 230, 36));

        lblApellidoMaterno.setFont(new java.awt.Font("Amazon Ember", 1, 20)); // NOI18N
        lblApellidoMaterno.setForeground(new java.awt.Color(143, 143, 143));
        lblApellidoMaterno.setText("Apellido Materno:");
        lblApellidoMaterno.setEnabled(false);
        add(lblApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, -1, -1));

        txtApellidoMaterno.setEditable(false);
        txtApellidoMaterno.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtApellidoMaterno.setForeground(new java.awt.Color(180, 154, 102));
        txtApellidoMaterno.setText("nombreCliente");
        txtApellidoMaterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143, 143, 143)));
        txtApellidoMaterno.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 230, 36));

        txtUsuario.setEditable(false);
        txtUsuario.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(180, 154, 102));
        txtUsuario.setText("nombreCliente");
        txtUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143, 143, 143)));
        txtUsuario.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 250, 36));

        lblUsuario.setFont(new java.awt.Font("Amazon Ember", 1, 20)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(143, 143, 143));
        lblUsuario.setText("Usuario:");
        lblUsuario.setEnabled(false);
        add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        lblContrasena.setFont(new java.awt.Font("Amazon Ember", 1, 20)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(143, 143, 143));
        lblContrasena.setText("Contraseña:");
        lblContrasena.setEnabled(false);
        add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        txtContrasena.setEditable(false);
        txtContrasena.setForeground(new java.awt.Color(180, 154, 102));
        txtContrasena.setText("xCosas");
        add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 230, 36));

        txtColonia.setEditable(false);
        txtColonia.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtColonia.setForeground(new java.awt.Color(180, 154, 102));
        txtColonia.setText("nombreCliente");
        txtColonia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143, 143, 143)));
        txtColonia.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        add(txtColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 250, 36));

        lblUsuario1.setFont(new java.awt.Font("Amazon Ember", 1, 20)); // NOI18N
        lblUsuario1.setForeground(new java.awt.Color(143, 143, 143));
        lblUsuario1.setText("Colonia:");
        lblUsuario1.setEnabled(false);
        add(lblUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        txtCalle.setEditable(false);
        txtCalle.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtCalle.setForeground(new java.awt.Color(180, 154, 102));
        txtCalle.setText("nombreCliente");
        txtCalle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143, 143, 143)));
        txtCalle.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 250, 36));

        lblNombres2.setFont(new java.awt.Font("Amazon Ember", 1, 20)); // NOI18N
        lblNombres2.setForeground(new java.awt.Color(143, 143, 143));
        lblNombres2.setText("Calle:");
        add(lblNombres2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        txtCiudad.setEditable(false);
        txtCiudad.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtCiudad.setForeground(new java.awt.Color(180, 154, 102));
        txtCiudad.setText("nombreCliente");
        txtCiudad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143, 143, 143)));
        txtCiudad.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 230, 36));

        lblContrasena1.setFont(new java.awt.Font("Amazon Ember", 1, 20)); // NOI18N
        lblContrasena1.setForeground(new java.awt.Color(143, 143, 143));
        lblContrasena1.setText("Ciudad:");
        lblContrasena1.setEnabled(false);
        add(lblContrasena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, -1, -1));

        txtNumeroExterior.setEditable(false);
        txtNumeroExterior.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtNumeroExterior.setForeground(new java.awt.Color(180, 154, 102));
        txtNumeroExterior.setText("nombreCliente");
        txtNumeroExterior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143, 143, 143)));
        txtNumeroExterior.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        add(txtNumeroExterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 230, 36));

        lblApellidoPaterno1.setFont(new java.awt.Font("Amazon Ember", 1, 20)); // NOI18N
        lblApellidoPaterno1.setForeground(new java.awt.Color(143, 143, 143));
        lblApellidoPaterno1.setText("# exterior:");
        lblApellidoPaterno1.setEnabled(false);
        add(lblApellidoPaterno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));

        txtCodigoPostal.setEditable(false);
        txtCodigoPostal.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtCodigoPostal.setForeground(new java.awt.Color(180, 154, 102));
        txtCodigoPostal.setText("nombreCliente");
        txtCodigoPostal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143, 143, 143)));
        txtCodigoPostal.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        add(txtCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 230, 36));

        lblApellidoMaterno1.setFont(new java.awt.Font("Amazon Ember", 1, 20)); // NOI18N
        lblApellidoMaterno1.setForeground(new java.awt.Color(143, 143, 143));
        lblApellidoMaterno1.setText("Código postal:");
        lblApellidoMaterno1.setEnabled(false);
        add(lblApellidoMaterno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVistaEditarPerfil.png"))); // NOI18N
        fondo.setToolTipText("");
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Cambia la vista actual a la vista principal del cliente.
    *
    * @param evt El evento de acción que desencadena este método.
    */
    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        ventana.cambiarVistaCliente();
    }//GEN-LAST:event_btnInicioActionPerformed
    
    /**
    * Cambia la vista del perfil del cliente.
    *
    * @param evt El evento de acción que desencadena este método.
    */
    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerfilActionPerformed

    /**
    * Cambia la vista del historial de operaciones totales.
    *
    * @param evt El evento de acción que desencadena este método.
    */
    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
        ventana.cambiarVistaHistorial();
    }//GEN-LAST:event_btnHistorialActionPerformed

    /**
    * Cambia la vista actual a la pantalla de inicio del banco.
    *
    * @param evt El evento de acción que desencadena este método.
    */
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        if(ventana.mostrarConfirmacion("¿Seguro que querer cerrar sesión?", "Cerrar sesión")){
            ventana.setCliente(null);
            ventana.setCuenta(null);
            ventana.cambiarVistaInicio();
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
    * Carga los datos originales del cliente y su domicilio, luego desactiva los botones de guardar y cancelar
    * y desactiva los campos de edición.
    * @param evt Evento de acción generado por el botón.
    */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cargarDatos();
        
        btnGuardarCambios.setEnabled(false);
        btnCancelar.setEnabled(false);
        desactivarCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
    * Método que se ejecuta cuando se presiona el botón de editar.
    * Activa los botones de guardar y cancelar y activa los campos de edición.
    * @param evt Evento de acción generado por el botón.
    */
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        btnCancelar.setEnabled(true);
        btnGuardarCambios.setEnabled(true);
        activarCampos();
    }//GEN-LAST:event_btnEditarActionPerformed

    
    /**
    * Método que se ejecuta cuando se presiona el botón de guardar cambios.
    * Guarda los datos editados del cliente y su domicilio, luego valida los datos y, si son válidos,
    * desactiva los botones de guardar y cancelar y desactiva los campos de edición.
    * @param evt Evento de acción generado por el botón.
    */
    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        // TODO add your handling code here:
        guardarDatos();
        validarDatos();
        if(camposValidados){
            try {
                IClienteDAO clienteDAO = new ClienteDAO(ventana.getConexion());
                IDomicilioDAO domicilioDAO = new DomicilioDAO(ventana.getConexion());
                domicilioDAO.actualizar(domicilioDTO, clienteActual.getIdCliente());
                
                domicilioActual = domicilioDAO.existe(clienteActual.getIdCliente());
                
                clienteDAO.actualizar(clienteDTO, clienteActual.getIdCliente());
                clienteActual  = clienteDAO.existe(clienteActual.getIdCliente());
                ventana.setDomicilio(domicilioActual);
                ventana.setCliente(clienteActual);
                
                
            } catch (PersistenciaException ex) {
                Logger.getLogger(VistaEditarPerfil.class.getName()).log(Level.SEVERE, null, ex);
            }
            cargarDatos();
            btnCancelar.setEnabled(false);
            btnGuardarCambios.setEnabled(false);
            desactivarCampos();
        }
        
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed
    
    /**
    * Activa los campos de edición.
    */
    private void activarCampos(){
        txtNombre.setEditable(true);
        txtApellidoPaterno.setEditable(true);
        txtApellidoMaterno.setEditable(true);
        txtUsuario.setEditable(true);
        txtContrasena.setEditable(true);
        
        txtCalle.setEditable(true);
        txtColonia.setEditable(true);
        txtCiudad.setEditable(true);
        txtNumeroExterior.setEditable(true);
        txtCodigoPostal.setEditable(true);
    }
    
    /**
     * Desactiva los campos de edición.
     */
    private void desactivarCampos(){
        txtNombre.setEditable(false);
        txtApellidoPaterno.setEditable(false);
        txtApellidoMaterno.setEditable(false);
        txtUsuario.setEditable(false);
        txtContrasena.setEditable(false);
        
        txtCalle.setEditable(false);
        txtColonia.setEditable(false);
        txtCiudad.setEditable(false);
        txtNumeroExterior.setEditable(false);
        txtCodigoPostal.setEditable(false);
    }
    
    /**
    * Carga los datos del cliente y su domicilio en los campos correspondientes.
    */
    private void cargarDatos(){
        txtNombre.setText(clienteActual.getNombre());
        txtApellidoPaterno.setText(clienteActual.getApellidoPaterno());
        txtApellidoMaterno.setText(clienteActual.getApellidoMaterno());
        txtUsuario.setText(clienteActual.getUsuario());
        txtContrasena.setText("");
        
        txtCalle.setText(domicilioActual.getCalle());
        txtColonia.setText(domicilioActual.getColonia());
        txtCiudad.setText(domicilioActual.getCiudad());
        txtCodigoPostal.setText(domicilioActual.getCodigoPostal());
        txtNumeroExterior.setText(domicilioActual.getNumeroExterior());
    }

    /**
    * Guarda los datos editados del cliente y su domicilio en objetos DTO.
    */
    private void guardarDatos(){
        clienteDTO = new ClienteNuevoDTO();
        domicilioDTO = new DomicilioNuevoDTO();
        
        clienteDTO.setNombres(txtNombre.getText());
        clienteDTO.setApellidoPaterno(txtApellidoPaterno.getText());
        clienteDTO.setApellidoMaterno(txtApellidoMaterno.getText());
        clienteDTO.setContrasena(new String(txtContrasena.getPassword()));
        clienteDTO.setUsuario(txtUsuario.getText());
        
        
        domicilioDTO.setCalle(txtCalle.getText());
        domicilioDTO.setCiudad(txtCiudad.getText());
        domicilioDTO.setCodigoPostal(txtCodigoPostal.getText());
        domicilioDTO.setColonia(txtColonia.getText());
        domicilioDTO.setNumeroExterior(txtNumeroExterior.getText());
    }
    
    /**
    * Valida los datos ingresados por el usuario.
    */
    private void validarDatos(){
        ValidadorCampos valida = new ValidadorCampos();
        try {
            clienteDTO.esValido3();
            valida.validaSeccionDatosPersonales(clienteDTO);
            valida.validaSeccionDatosCuenta(clienteDTO.getUsuario(), clienteDTO.getContrasena());
            
            
            domicilioDTO.esValido();
            valida.validaSeccionDatosDomicilio(domicilioDTO);
            camposValidados = true;
        } catch (ValidacionDTOException ex) {
            camposValidados = false;
            ventana.mostrarAviso(ex.getMessage());
//            Logger.getLogger(VistaRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel iconAjustes;
    private javax.swing.JLabel iconCerrarSesion;
    private javax.swing.JLabel iconHistorial;
    private javax.swing.JLabel iconInicio;
    private javax.swing.JLabel iconLogo;
    private javax.swing.JLabel iconPerfil;
    private javax.swing.JLabel lblApellidoMaterno;
    private javax.swing.JLabel lblApellidoMaterno1;
    private javax.swing.JLabel lblApellidoPaterno;
    private javax.swing.JLabel lblApellidoPaterno1;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblContrasena1;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblNombres1;
    private javax.swing.JLabel lblNombres2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroExterior;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
