package bancodelsol;

/**
 *
 * @author karim
 */
public class VistaInicio extends javax.swing.JPanel {

    /**
     * Creates new form VistaInicio
     */
    private  Ventana ventana;
    /**
     * Creates new form VistaCliente
     */
    public VistaInicio(Ventana ventana ) {
        this.ventana = ventana;
        initComponents();
        btnRetiro.setText("<html>Retiro sin<br>cuenta</html>");
        lblEslogan.setText("<html>\"El banco que cuida de<br>ti y de tu futuro\"</html>");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInicioSesion = new javax.swing.JButton();
        btnRetiro = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        btnNosotros = new javax.swing.JButton();
        lblBanco = new javax.swing.JLabel();
        lblEslogan = new javax.swing.JLabel();
        lblPiePagina = new javax.swing.JLabel();
        iconFamilia = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicioSesion.setBackground(new java.awt.Color(180, 154, 102));
        btnInicioSesion.setFont(new java.awt.Font("Amazon Ember", 0, 18)); // NOI18N
        btnInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnInicioSesion.setText("Iniciar Sesión");
        btnInicioSesion.setBorderPainted(false);
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });
        add(btnInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 150, 45));

        btnRetiro.setBackground(new java.awt.Color(180, 154, 102));
        btnRetiro.setFont(new java.awt.Font("Amazon Ember", 0, 18)); // NOI18N
        btnRetiro.setForeground(new java.awt.Color(255, 255, 255));
        btnRetiro.setText("Retiro sin cuenta");
        btnRetiro.setBorderPainted(false);
        btnRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroActionPerformed(evt);
            }
        });
        add(btnRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 180, 45));

        btnInicio.setBackground(new java.awt.Color(143, 143, 143));
        btnInicio.setFont(new java.awt.Font("Amazon Ember Light", 0, 18)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Inicio");
        btnInicio.setBorder(null);
        btnInicio.setBorderPainted(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 105, 129, 36));

        btnRegistro.setBackground(new java.awt.Color(143, 143, 143));
        btnRegistro.setFont(new java.awt.Font("Amazon Ember Light", 0, 16)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistro.setText("Hazte cliente");
        btnRegistro.setBorderPainted(false);
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 105, 129, 36));

        btnNosotros.setBackground(new java.awt.Color(143, 143, 143));
        btnNosotros.setFont(new java.awt.Font("Amazon Ember Light", 0, 18)); // NOI18N
        btnNosotros.setForeground(new java.awt.Color(255, 255, 255));
        btnNosotros.setText("Nosotros");
        btnNosotros.setBorderPainted(false);
        btnNosotros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNosotrosActionPerformed(evt);
            }
        });
        add(btnNosotros, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 105, 129, 36));

        lblBanco.setFont(new java.awt.Font("TrajanusBricks", 0, 44)); // NOI18N
        lblBanco.setForeground(new java.awt.Color(149, 120, 64));
        lblBanco.setText("banco del sol");
        add(lblBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        lblEslogan.setFont(new java.awt.Font("Amazon Ember Light", 0, 18)); // NOI18N
        lblEslogan.setForeground(new java.awt.Color(33, 33, 33));
        add(lblEslogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 230, 70));

        lblPiePagina.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        lblPiePagina.setForeground(new java.awt.Color(255, 255, 255));
        lblPiePagina.setText("© Banco del Sol 2024");
        add(lblPiePagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 545, 170, 20));

        iconFamilia.setFont(new java.awt.Font("Amazon Ember", 0, 16)); // NOI18N
        iconFamilia.setForeground(new java.awt.Color(255, 255, 255));
        add(iconFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 180, 322, 246));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconLogo(2).png"))); // NOI18N
        add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgInicio.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
        // TODO add your handling code here:
        ventana.cambiarVistaInicioSesion();
    }//GEN-LAST:event_btnInicioSesionActionPerformed

    private void btnRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetiroActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
        ventana.cambiarVistaRegistro();
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnNosotrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNosotrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNosotrosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnInicioSesion;
    private javax.swing.JButton btnNosotros;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnRetiro;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel iconFamilia;
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblEslogan;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblPiePagina;
    // End of variables declaration//GEN-END:variables
}
